channels:
  - conda-forge/label/jupyterlab_alpha
  - conda-forge/label/notebook_alpha
  - conda-forge/label/jupyterlab_fonts_alpha
  - conda-forge/label/jupyterlab_deck_alpha
  - conda-forge
  - nodefaults
platforms:
  - linux-64
dependencies:
  # jupyter
  - ipywidgets >=8.1.1,<9.0.0
  - jupyterlab >=4.1.0a3,<5.0.0
  - notebook >=7.1.0a0,<8
  # images
  - imagemagick
  # demo
  - jupyterlab-deck >=0.2.0a0
  ### .github/environment.yml ###
  # more runtimes
  - nodejs >=20,<21
  - yarn ==3.6.4
  # fix
  - ruff
  - nbstripout
  - scour
  # test
  - pytest
  - pytest-cov
  - pytest-html
  ### docs/environment.yml ###
  # runtimes
  - python >=3.11,<3.12
  # run
  - doit-with-toml
  - importnb
  - pyyaml
  - tomli
  # build
  - flit-core >=3.9.0,<4
  - pip
  - python-build
  # docs
  - docutils >=0.19
  - myst-nb
  - nbconvert
  - pydata-sphinx-theme
  - sphinx-copybutton
  - sphinxcontrib-mermaid
  - sphinxext-rediraffe
  - tomli-w
  ### docs/environment.yml ###
  ### .github/environment.yml ###
