channels:
  - conda-forge
  - nodefaults
platforms:
  - linux-64
dependencies:
  ### docs/environment.yml ###
  # runtimes
  - python >=3.11,<3.12
  # run
  - doit-with-toml
  - importnb
  - pyyaml
  - tomli
  # build
  - flit-core >=3.9.0,<4
  - pip
  - python-build
  - yarn ==3.6.4
  # docs
  - docutils >=0.19
  - myst-nb
  - nbconvert
  - pydata-sphinx-theme
  - python-libarchive-c
  - sphinx-copybutton
  - sphinxcontrib-mermaid
  - sphinxext-rediraffe
  - tomli-w
  ### docs/environment.yml ###
